apiVersion: v1
kind: Service
metadata:
  name: import-export-service
spec:
  ports:
    - port: 8080
      name: http
  type: LoadBalancer
  selector:
    app: import-export-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: import-export-deployment
spec:
  selector:
    matchLabels:
      app: import-export-deployment
  template:
    metadata:
      labels:
        app: import-export-deployment
    spec:
      containers:
        - name: import-export-container
          image: skaffold-jib
          ports:
            - containerPort: 8080